### PR TITLE
Entropy Creeper Enhancements

### PR DESCRIPTION
**Pull request by pixar02**
Solves #18, #9
Used default Creeper Spawn settings.

Done:
- [x] Entropy Creeper spawns naturally (Default Creeper settings)
- [x] Documented (to the best of my abilities, a lot wasn't available) 
      - Added info for testing ( 'BiomSelectors.all()' and enter End/Nether)
 - [x] Teleport player when inside range to somewhere inside the range.
      - Change 'getClosestPlayer(... ,false)' for testing
 - [x] Shuffle explosion

Refinement:
- Add Configurable Spawn Settings (Biomes list, spawnrate,....)

### CODE REVIEW

**Comment by JoeyDP** [comment]
Let me know once this is ready to be merged in main. The spawning looks good, but I'll wait until the shuffling is done.

**Comment by BertJorissen** [comment]
A small comment: in loading the game, I saw that there were 51 EntropyCreepers and 8 'normal' creepers. The mobs from the mod spawn more frequently. I see that the 'normal' weight of 100 is chose, though I'm not sure if the creepers can spawn in groups of 2. Anyway, I also didn't find the original file from Minecraft describing the spawn rate for reference.
The rest seems to work fine.

**Review by BertJorissen — APPROVED** [review]

**Comment by pixar02** [comment]
> A small comment: in loading the game, I saw that there were 51 EntropyCreepers and 8 'normal' creepers. The mobs from the mod spawn more frequently. I see that the 'normal' weight of 100 is chose, though I'm not sure if the creepers can spawn in groups of 2. Anyway, I also didn't find the original file from Minecraft describing the spawn rate for reference. The rest seems to work fine.

Groups of 2 is already half of what the default is...
https://fabricmc.net/wiki/tutorial:entity-old (in the section about natural spawning)
Didn't find any other data for it.

**Comment by pixar02** [comment]
> Let me know once this is ready to be merged in main. The spawning looks good, but I'll wait until the shuffling is done.
Ready for Review

**Review by JoeyDP — APPROVED** [review]

**Pull request merged**
