### PR TITLE
Throwable Electrons 

### PR DESCRIPTION
**Pull request by thdaele**
Pull request for issue #4 

- [x] Add a new throwable entity for the Electron
- [x] Add correct textures to thrown Electron
- [x] Configure the electron item to spawn the entity
- [x] Change the logic of the thrown electron to go straight and not slow down
- [x] Make sure the entity despawns after a while
- [x] Test whether everything works with a separate server and client
- [x] Submit and document pull request for review
- [x] Create new issues based on this prototype to refine how it works

### CODE REVIEW

**Comment by JoeyDP** [comment]
Great work on getting a working example so fast! I see it's still a work in progress, but seeing the electron fly out already is quite nice.

I also tried it with separate client and server, but that didn't seem to work yet. Honestly the entire networking aspect and server/client logic still confuses me too, so I can't immediately say what the problem is. When you try it out, you do get a useful stack trace of the error that should help you get started. If you can fix that and maybe clean up the code a bit, then we can merge this into `main` so other people can use it for inspiration.

**Comment by JoeyDP** [comment]
I've been doing some experiments with the network code and it seems like you do not need to write any custom spawn packets at all (despite what the wiki says). If you don't override the `createSpawnPacket` function in `ElectronEntity` and also remove the other networking code, everything works fine for me. Can you confirm that this is actually the case?

It would also be useful if you can merge the upstream main branch into yours for the pull request.

The documentation might be outdated and to be fair that part of the wiki was quite cringy to read..
image
image

**Comment by thdaele** [comment]
I will try it without the network code and merge the upstream tomorrow. I tried implementing it without the network code at first, but then I had lot of problems with the outdated mappings (different method names) and member variables that got changed from public to private. It was all very confusing for using fabric for the first time. Wiki is indeed very outdated and cringe, the network code added is basically the same as the network code from minecraft so I didn't understand why it is needed as well.

**Comment by thdaele** [comment]
The unnecessary network code is removed and the upstream is merged. The pull request is ready to review.

**Review by JoeyDP — APPROVED** [review]

**Pull request merged**
