### PR TITLE
Entropy creeper

### PR DESCRIPTION
**Pull request by JoeyDP**
Sound and polishing edge cases.

### CODE REVIEW

**Review by pixar02 — CHANGES_REQUESTED** [review]
Instead of setting the Blocks that "should not be moved" to air, maybe just ignore them.
Making a water fountain was nice, also leaves are just destroyed (while leaves placed while in creative don't despawn).

**Comment by JoeyDP** [comment]
The issue with 'just ignoring them' is that blocks also can't move to their place. If you for example have an entropy creeper explosion on grass with lots of actual grass tiles (the crosses), then they wouldn't be replaced and you wouldn't get a very chaotic result in that space.

I use the piston breakable trick to roughly determine the blocks we don't want to have floating, like tall grass and half doors. Feel free to suggest another solution.

**Comment by pixar02** [comment]
> The issue with 'just ignoring them' is that blocks also can't move to their place. If you for example have an entropy creeper explosion on grass with lots of actual grass tiles (the crosses), then they wouldn't be replaced and you wouldn't get a very chaotic result in that space.
> 
> I use the piston breakable trick to roughly determine the blocks we don't want to have floating, like tall grass and half doors. Feel free to suggest another solution.

Since we know both locations we can check if we can place the block at that position (should fix the grass).
image

image

**Comment by JoeyDP** [comment]
> Since we know both locations we can check if we can place the block at that position (should fix the grass).

So you mean just leaving the grass where it was?

> As for Doors, that I can understand. (But instead of removing them they should be dropped)

Placing air over them seems to drop them already. Might just be if you only overwrite half the door or something.

I suggest we merge for now and schedule an in depth testing of the entropy creeper where we try to come up with a bunch of edge cases and define what we want to happen in each one.

**Comment by pixar02** [comment]
> > Since we know both locations we can check if we can place the block at that position (should fix the grass).
> 
> So you mean just leaving the grass where it was?

We can place something over the grass, we just can't place grass itself.

> > As for Doors, that I can understand. (But instead of removing them they should be dropped)
> Placing air over them seems to drop them already. Might just be if you only overwrite half the door or something.

Yes, only when you "break" the door (as a none player)  does it drop a door.

**Comment by JoeyDP** [comment]
I'm not sure what you want me to change anymore.. Feel free to just commit it yourself if you feel like it or otherwise if there is nothing actually wrong with this PR, you can make an issue for it and merge the PR.

**Comment by JoeyDP** [comment]
> I suggest we merge for now and schedule an in depth testing of the entropy creeper where we try to come up with a bunch of edge cases and define what we want to happen in each one.

Would this be okay with you?

**Review by pixar02 — APPROVED** [review]

**Pull request merged**
